spring:
  application:
    name: dubbo-customer
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
dubbo:
  application:
    id: dubbo-provider
  scan:
    base-packages: io.github.xyz.spring.boot.dubbo.service
  registry:
    address: zookeeper://127.0.0.1:2181
    subscribe: false # 只注册
