spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 172.16.1.54:9300
      cluster-name: es-cn-45910glzw000g5esz
#      properties:
#        xpack.security.user: elastic:Ela%Ts6Op!cU
  elasticsearch:
    jest:
      uris:
        - http://172.16.1.54:9200
      username: elastic
      password: Ela%Ts6Op!cU
