spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    id: dubbo-provider
  scan:
    base-packages: io.github.xyz.spring.boot.dubbo.service
  registry:
    address: zookeeper://127.0.0.1:2181
    register: false # 只订阅
  consumer:
    check: false # 不检查

