spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch # 集群名称
  elasticsearch:
    jest:
      uris:
        - http://127.0.0.1:9200 # 多个使用数组
      username: elastic  # 账号
      password: xxxx # 密码
