spring:
  application:
    name: sentinel-apollo-push
  cloud:
    sentinel:
      transport:
        port: 8719 # 向sentinel-dashboard传输数据的端口 默认:8719
        dashboard: localhost:8100 # sentinel-dashboard
      log:
        dir: ./logs # 默认值${home}/logs/csp/
        switch-pid: true # 日志带上线程id
      datasource:
        flow: # 流控规则
          apollo:
            namespaceName: application
            flowRulesKey: sentinel.flowRules # 注意该key必须固定
            rule-type: flow #flow,degrade,authority,system, param-flow
#        degrade: # 熔断降级规则
#          apollo:
#            namespaceName: application
#            flowRulesKey: degrades
#            rule-type: degrade
#        authority: # 授权规则
#          apollo:
#            namespaceName: application
#            flowRulesKey: authoritys
#            rule-type: authority
#        system: # 系统规则
#          apollo:
#            namespaceName: application
#            flowRulesKey: systems
#            rule-type: system
#        param-flow: # 热点规则
#          apollo:
#            namespaceName: application
#            flowRulesKey: paramflows
#            rule-type: param-flow
app:
  id: ${spring.application.name}
apollo:
  meta: http://127.0.0.1:8080
  cacheDir: ./apolloconfig  # 缓存文件位置