oss:
  sts:
    access-key-id: abc
    access-key-secret: edf
    role-arn: hsf
    role-session-name: dfdg
    policy:
      version: 2.0
      statement:
        - effect: Allow
          resource:
            - ab
            - cd
          condition:
            source-ip:
              - 192.68
