server:
  port: 7800
  servlet:
    context-path: /kafka
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092 # 本地kafka地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0 # 重试
      #bootstrap-servers: 127.0.0.1:9092 # 本地kafka地址
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: spring_kafka # 必须设置  aliyun group: t3_group_ts_passenger_account
