spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.56.10:9200
      cluster-name: elasticsearch
      properties:
        xpack.security.user: elastic:123456