spring:
  application:
    name: dubbo-dtx-lisi-bank
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: lisi-seata-service-group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank02?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
dubbo:
  scan:
    base-packages: io.github.xyz.spring.boot.rocketmq.lisi.service
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: dubbo-dtx-lisi-bank

#mybatis:
#  mapper-locations: classpath:io/github/xyz/spring/boot/rocketmq/lisi/mapper/xml/*.xml
#  type-aliases-package: io.github.xyz.spring.boot.rocketmq.lisi.model

logging:
  level:
    org.springframework: warn
    com.netflix.config: error
    org.apache.dubbo.config: error
    org.apache.dubbo.remoting: warn
    io.seata.core.rpc.netty.AbstractRpcRemoting: warn
    io.seata.core.rpc.netty.NettyPoolableFactory: warn
    io.github.xyz.spring.boot.rocketmq.lisi.mapper: debug
    io.seata.core.rpc.netty.NettyClientChannelManager: warn
    com.alibaba.cloud.dubbo.service.DubboMetadataServiceExporter: warn

server:
  port: 7101

rocketmq:
  name-server: localhost:9876
  producer:
    group: dubbo-dtx-lisi-bank
#    send-message-timeout: 300000