spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank01?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
# 公共日志级别设置
logging:
  level:
    org.springframework: warn
    com.netflix.config: error
    org.apache.dubbo.config: error
    org.apache.dubbo.remoting: warn
    io.seata.core.rpc.netty.AbstractRpcRemoting: warn
    io.seata.core.rpc.netty.NettyPoolableFactory: warn
    io.github.xyz.spring.boot.rocketmq.lisi.mapper: debug
    io.seata.core.rpc.netty.NettyClientChannelManager: warn
    com.alibaba.cloud.dubbo.service.DubboMetadataServiceExporter: warn