logging:
  level:
    org.springframework: warn
    com.netflix.config: error
    org.apache.dubbo.config: error
    org.apache.dubbo: warn
    io.seata.core.rpc.netty.AbstractRpcRemoting: warn
    io.seata.core.rpc.netty.NettyPoolableFactory: warn
    io.github.xyz.spring.boot.rocketmq.lisi.mapper: debug
    io.seata.core.rpc.netty.NettyClientChannelManager: warn
    com.alibaba.cloud.dubbo.service.DubboMetadataServiceExporter: warn